Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c115dbd34c69a004 # Amazon Linux AMI in N.Virginia
      Tags:
        - Key: Name
          Value: A simple example
